---
version: "3.0"

x-build: &x-build
  context: .
  dockerfile: Dockerfile

services:

  ############################################
  #
  # Prod and Dev Services
  #
  ############################################
  site:
    build:
      <<: *x-build
      args:
        NODE_ENV: production
    image: ffl-site-v2
    entrypoint: ["yarn", "start"]  # Likely need to change this entrypoint for prod
    ports:
      - "5001:3000"
    networks:
      - bubble
      - earth

  site-dev:
    build:
      <<: *x-build
      args:
        NODE_ENV: development
    image: ffl-site-v2-dev
    entrypoint: ["yarn", "--modules-folder", "/etc/ffl-site", "start"]
    ports:
      - "5001:3000"
    networks:
      - bubble
      - earth
    volumes:
      - .:/app:rw

  ############################################
  #
  # Dev Tools
  #
  ############################################
  dev-tool: &dev-tool
    build:
      <<: *x-build
      args:
        NODE_ENV: development
    image: ffl-site-v2-dev-tool
    networks:
      - bubble
    volumes:
      - .:/app:rw

  generate-code:
    <<: *dev-tool
    entrypoint: ["yarn", "--modules-folder", "/etc/ffl-site", "generate"]
    stdin_open: true  # Allow runner to interact with command
    tty: true

  reformat:
    <<: *dev-tool
    entrypoint: ["yarn", "--modules-folder", "/etc/ffl-site", "reformat"]


networks:
  bubble:
    internal: True
  earth:
    external: True
