---
version: "3.0"

x-build: &x-build
  context: .
  dockerfile: Dockerfile

services:

  ############################################
  #
  # Prod and Dev Services
  #
  ############################################
  site:
    build:
      <<: *x-build
      args:
        NODE_ENV: production
    image: ffl-site-v2
    entrypoint: ["yarn", "start"]  # Likely need to change this entrypoint for prod
    networks:
      - bubble
      - earth

  site-dev:
    build:
      <<: *x-build
      args:
        NODE_ENV: development
    image: ffl-site-v2-dev
    entrypoint: ["yarn", "--modules-folder", "/etc/ffl-site", "start"]
    networks:
      - bubble
      - earth
    volumes:
      - .:/app:rw

  ingress: &ingress
    image: nginx
    environment:
      - NGINX_PORT=80
    ports:
      - "80:80"
    volumes:
      - ./ingress/prod:/etc/nginx/templates
    networks:
      - bubble
      - earth
    depends_on:
      - site

  ingress-dev:
    <<: *ingress
    volumes:
      - ./ingress/dev:/etc/nginx/templates
    depends_on:
      - site-dev

  ############################################
  #
  # Dev Tools
  #
  ############################################
  dev-tool: &dev-tool
    build:
      <<: *x-build
      args:
        NODE_ENV: development
    image: ffl-site-v2-dev-tool
    networks:
      - bubble
    volumes:
      - .:/app:rw

  generate-code:
    <<: *dev-tool
    entrypoint: ["yarn", "--modules-folder", "/etc/ffl-site", "generate"]
    stdin_open: true  # Allow runner to interact with command
    tty: true

  reformat:
    <<: *dev-tool
    entrypoint: ["yarn", "--modules-folder", "/etc/ffl-site", "reformat"]


networks:
  bubble:
    internal: True
  earth:
    external: True
